repos:
  - repo: https://github.com/astral-sh/uv-pre-commit
    # uv version.
    rev: 0.7.8
    hooks:
      - id: uv-lock
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
    rev: v0.11.12
    hooks:
      # Run the linter.
      - id: ruff-check
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
  # pyright is a static checker for python
  # This will help in imports and return values check
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.401
    hooks:
    - id: pyright